<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3u2TREGjAc7axsrEhHhx'."\n".'NpjlqZZ9f9c0+8a5V0wM7QdtuaNF6C/kgbu2nCPNjiKr+4TsPzQ0ttHQwKdm7irj'."\n".'7BwVvsrywYdHpFGZeh5TEc/xJVFSDvtFcVD8t6fzVvGm9f0PP6CsN8R/wWreKZ28'."\n".'L36+W0uN0T/wV3FmgYXLKpi7fhUSJaPe8qntaz4VpAvz+saAGS6wktmd3Xl2dnV6'."\n".'nMgxB2V6P5GuCbdnX31sUVFTCgsTASHJueMLmkN0d0RKKK/adkCIgHupEGfsZben'."\n".'ncoqNUNvHe7Lr7ZycvUD+hM+e2kkZ1YscAHoWvW57vzwA978SBtFACWkbI9SDet3'."\n".'MwIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
