<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWRvLcZ5\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWRvLcZ5/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWRvLcZ5.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWRvLcZ5\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerWRvLcZ5\appAppKernelDevDebugContainer([
    'container.build_hash' => 'WRvLcZ5',
    'container.build_id' => 'b24f526e',
    'container.build_time' => 1756978898,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWRvLcZ5');
